// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package database

import (
	"context"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (id, email, created_at, updated_at)
VALUES
    (gen_random_uuid(), NOW(), NOW(), $1)
RETURNING
    id, email, created_at, updated_at
`

func (q *Queries) CreateUser(ctx context.Context, updatedAt time.Time) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, updatedAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
